/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CTScan {
  'id' : ScanId,
  'analysisResult' : [] | [TumorDetectionResult],
  'patientId' : PatientId,
  'scanImage' : Uint8Array,
}
export interface ExternalApiConfig { 'endpointUrl' : string, 'apiKey' : string }
export type PatientId = string;
export type ScanId = bigint;
export interface TumorDetectionResult {
  'probability' : number,
  'tumorFound' : boolean,
  'maskImage' : Uint8Array,
  'stage' : TumorStage,
  'confidence' : number,
}
export type TumorStage = { 'stage0' : null } |
  { 'stage1' : null } |
  { 'stage2' : null } |
  { 'stage3' : null } |
  { 'stage4' : null };
export interface UserProfile {
  'name' : string,
  'specialization' : string,
  'department' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'analyzeScan' : ActorMethod<[ScanId], ScanId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'configureExternalApi' : ActorMethod<[ExternalApiConfig], undefined>,
  'getAllScans' : ActorMethod<[], Array<CTScan>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExternalApiConfig' : ActorMethod<[], [] | [ExternalApiConfig]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVersion' : ActorMethod<[], string>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'readScan' : ActorMethod<[ScanId], CTScan>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'uploadScan' : ActorMethod<[PatientId, Uint8Array], ScanId>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];