/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ScanId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalApiConfig = IDL.Record({
  'endpointUrl' : IDL.Text,
  'apiKey' : IDL.Text,
});
export const TumorStage = IDL.Variant({
  'stage0' : IDL.Null,
  'stage1' : IDL.Null,
  'stage2' : IDL.Null,
  'stage3' : IDL.Null,
  'stage4' : IDL.Null,
});
export const TumorDetectionResult = IDL.Record({
  'probability' : IDL.Float64,
  'tumorFound' : IDL.Bool,
  'maskImage' : IDL.Vec(IDL.Nat8),
  'stage' : TumorStage,
  'confidence' : IDL.Float64,
});
export const PatientId = IDL.Text;
export const CTScan = IDL.Record({
  'id' : ScanId,
  'analysisResult' : IDL.Opt(TumorDetectionResult),
  'patientId' : PatientId,
  'scanImage' : IDL.Vec(IDL.Nat8),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'specialization' : IDL.Text,
  'department' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'analyzeScan' : IDL.Func([ScanId], [ScanId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'configureExternalApi' : IDL.Func([ExternalApiConfig], [], []),
  'getAllScans' : IDL.Func([], [IDL.Vec(CTScan)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExternalApiConfig' : IDL.Func(
      [],
      [IDL.Opt(ExternalApiConfig)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVersion' : IDL.Func([], [IDL.Text], ['query']),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'readScan' : IDL.Func([ScanId], [CTScan], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'uploadScan' : IDL.Func([PatientId, IDL.Vec(IDL.Nat8)], [ScanId], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ScanId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalApiConfig = IDL.Record({
    'endpointUrl' : IDL.Text,
    'apiKey' : IDL.Text,
  });
  const TumorStage = IDL.Variant({
    'stage0' : IDL.Null,
    'stage1' : IDL.Null,
    'stage2' : IDL.Null,
    'stage3' : IDL.Null,
    'stage4' : IDL.Null,
  });
  const TumorDetectionResult = IDL.Record({
    'probability' : IDL.Float64,
    'tumorFound' : IDL.Bool,
    'maskImage' : IDL.Vec(IDL.Nat8),
    'stage' : TumorStage,
    'confidence' : IDL.Float64,
  });
  const PatientId = IDL.Text;
  const CTScan = IDL.Record({
    'id' : ScanId,
    'analysisResult' : IDL.Opt(TumorDetectionResult),
    'patientId' : PatientId,
    'scanImage' : IDL.Vec(IDL.Nat8),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'specialization' : IDL.Text,
    'department' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'analyzeScan' : IDL.Func([ScanId], [ScanId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'configureExternalApi' : IDL.Func([ExternalApiConfig], [], []),
    'getAllScans' : IDL.Func([], [IDL.Vec(CTScan)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExternalApiConfig' : IDL.Func(
        [],
        [IDL.Opt(ExternalApiConfig)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVersion' : IDL.Func([], [IDL.Text], ['query']),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'readScan' : IDL.Func([ScanId], [CTScan], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'uploadScan' : IDL.Func([PatientId, IDL.Vec(IDL.Nat8)], [ScanId], []),
  });
};

export const init = ({ IDL }) => { return []; };